### ISSUE TITLE
Davis, KIBA, DTC, Metz, and ToxCast

### ISSUE THREAD

**Issue by speakstone** [meyresearch/DL_protein_ligand_affinity#2]
Regarding the Davis, KIBA, DTC, Metz, and ToxCast datasets, could you please guide me to where I can find the prediction results using AlphaFold? I have delved deeply into your work and understand its immense value for drug discovery. Compared to the current cutting-edge algorithms, yours stands out as the most significant. As a newcomer to the research field, I sincerely hope for your guidance and response to my queries.

**Comment by rgorantla04** [comment]
You can find the Alphafold2 contact maps which we use for training the graph neural networks, by downloading the data as mentioned in the readme from  [here](https://uoe-my.sharepoint.com/:f:/g/personal/s2112695_ed_ac_uk/Ek7zFQJ5WUhIgEy6D1cvCjgBcVtLpQ0asZvPmjd8uv4afA?e=rekIFD) and to download alphafold2 structures for datasets which we didn't use in our project, you can find them with a PDB_ID or UniprotID, you can download from [here](https://alphafold.ebi.ac.uk/) and use our code [here](https://github.com/meyresearch/DL_protein_ligand_affinity/blob/main/misc/PDB2Cmap.ipynb) to get contact maps from the Alphafold2 predicted structures in the PDB format.
